import raw from "@/content/liturgy/liturgy.json";
import downloads from "@/content/liturgy/downloads.json";
import type { LiturgyDocument, LiturgyLine } from "./types";

/**
 * The converted liturgy. Generated by `npm run liturgy:convert` — edit the
 * source .docx and re-run rather than editing the JSON.
 *
 * The cast is needed because TypeScript widens the imported JSON's literal
 * unions (`kind`, `role`, `tone`) to `string`.
 */
export const LITURGY = raw as unknown as LiturgyDocument;

/**
 * Placeholder for the Serbian Romani Služebnik (Novi Sad, 1993), which exists
 * only in print. A scan is expected later. Kept in the data, deliberately not
 * rendered, so adding it is a matter of dropping the file into
 * `public/downloads/liturgy/` and re-running `npm run book`.
 */
export const SERBIAN_SLUZEBNIK_SCAN = {
  href: "/downloads/liturgy/serbian-sluzebnik-1993.pdf",
  label: "Serbian Romani Služebnik (Novi Sad, 1993) — scan",
  available: false,
} as const;

const DOWNLOAD_HREFS = new Set(downloads.files.map((f) => f.href));

/** Byte size by href, for showing the reader what they are about to fetch. */
const DOWNLOAD_BYTES = new Map(downloads.files.map((f) => [f.href, f.bytes]));

/**
 * Whether a download exists, according to the manifest written by
 * `npm run book`.
 *
 * Deliberately not an `existsSync` check: Next.js traces imports, not runtime
 * filesystem reads, so `public/` is not guaranteed to sit next to the running
 * function on a serverless deployment. A stale manifest shows a wrong link;
 * a failed `existsSync` would hide every download on production.
 */
export function hasDownload(href: string): boolean {
  return DOWNLOAD_HREFS.has(href);
}

/** Human-readable size, e.g. "268 KB". Empty when the file is not in the manifest. */
export function downloadSize(href: string): string {
  const bytes = DOWNLOAD_BYTES.get(href);
  if (bytes === undefined) return "";
  if (bytes < 1024 * 1024) return `${Math.round(bytes / 1024)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/** A run of text, or a footnote marker, in the order the reader meets them. */
export type LineToken =
  | { type: "text"; value: string }
  | { type: "note"; n: number };

/**
 * Splits a line into text and footnote markers.
 *
 * Line text is stored verbatim with `[[fn:N]]` markers where the source had a
 * footnote reference, so rendering has to walk the string rather than just
 * print it.
 */
export function tokenizeLine(line: LiturgyLine): LineToken[] {
  const tokens: LineToken[] = [];
  const pattern = /\[\[fn:(\d+)\]\]/g;
  let cursor = 0;
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(line.text)) !== null) {
    if (match.index > cursor) {
      tokens.push({ type: "text", value: line.text.slice(cursor, match.index) });
    }
    tokens.push({ type: "note", n: Number(match[1]) });
    cursor = match.index + match[0].length;
  }
  if (cursor < line.text.length) {
    tokens.push({ type: "text", value: line.text.slice(cursor) });
  }
  return tokens;
}

/**
 * Splits text on the `*` chant marks that divide sung phrases in the source.
 * Returned segments are trimmed and empty ones dropped, so a trailing `*`
 * does not produce a blank phrase.
 */
export function chantPhrases(text: string): string[] {
  return text
    .split("*")
    .map((phrase) => phrase.trim())
    .filter(Boolean);
}


