import raw from "@/content/liturgy/liturgy.json";
import type { LiturgyDocument, LiturgyLine } from "./types";

/**
 * The converted liturgy. Generated by `npm run liturgy:convert` — edit the
 * source .docx and re-run rather than editing the JSON.
 *
 * The cast is needed because TypeScript widens the imported JSON's literal
 * unions (`kind`, `role`, `tone`) to `string`.
 */
export const LITURGY = raw as unknown as LiturgyDocument;

/** Downloads offered on /liturgy. `available: false` renders nothing. */
export interface LiturgyDownload {
  key: string;
  href: string;
  label: string;
  meta: string;
  available: boolean;
}

/**
 * The Serbian Romani Služebnik (Novi Sad, 1993) exists only in print. A scan
 * is expected later; the entry is kept here so it is one flag away from going
 * live, and stays out of the UI until then.
 */
export const SERBIAN_SLUZEBNIK_SCAN: LiturgyDownload = {
  key: "serbian-sluzebnik-scan",
  href: "/downloads/liturgy/serbian-sluzebnik-1993.pdf",
  label: "Serbian Romani Služebnik (Novi Sad, 1993) — scan",
  meta: "PDF · pending digitisation",
  available: false,
};

/** A run of text, or a footnote marker, in the order the reader meets them. */
export type LineToken =
  | { type: "text"; value: string }
  | { type: "note"; n: number };

/**
 * Splits a line into text and footnote markers.
 *
 * Line text is stored verbatim with `[[fn:N]]` markers where the source had a
 * footnote reference, so rendering has to walk the string rather than just
 * print it.
 */
export function tokenizeLine(line: LiturgyLine): LineToken[] {
  const tokens: LineToken[] = [];
  const pattern = /\[\[fn:(\d+)\]\]/g;
  let cursor = 0;
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(line.text)) !== null) {
    if (match.index > cursor) {
      tokens.push({ type: "text", value: line.text.slice(cursor, match.index) });
    }
    tokens.push({ type: "note", n: Number(match[1]) });
    cursor = match.index + match[0].length;
  }
  if (cursor < line.text.length) {
    tokens.push({ type: "text", value: line.text.slice(cursor) });
  }
  return tokens;
}

/**
 * Splits text on the `*` chant marks that divide sung phrases in the source.
 * Returned segments are trimmed and empty ones dropped, so a trailing `*`
 * does not produce a blank phrase.
 */
export function chantPhrases(text: string): string[] {
  return text
    .split("*")
    .map((phrase) => phrase.trim())
    .filter(Boolean);
}

/** Footnote lookup by display number. */
export function footnoteText(n: number): string | null {
  return LITURGY.footnotes.find((f) => f.n === n)?.text ?? null;
}

/** Every footnote referenced by a section, in first-appearance order. */
export function sectionFootnotes(sectionId: string): number[] {
  const section = LITURGY.sections.find((s) => s.id === sectionId);
  if (!section) return [];

  const seen = new Set<number>();
  const ordered: number[] = [];
  for (const block of section.blocks) {
    if (block.kind !== "utterance") continue;
    for (const n of [...(block.sk?.notes ?? []), ...(block.rom?.notes ?? [])]) {
      if (seen.has(n)) continue;
      seen.add(n);
      ordered.push(n);
    }
  }
  return ordered;
}
