import {
  ArrowRight,
  BookOpen,
  Download,
  ExternalLink,
  FileText,
  HandHeart,
  Mic,
  Printer,
  SpellCheck,
} from "lucide-react";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CTASection from "@/components/CTASection";
import type { Locale } from "@/lib/i18n";
import { buildPath } from "@/lib/i18n/routes";
import { LITURGY, downloadSize, hasDownload } from "@/lib/liturgy/content";
import {
  CITATIONS,
  CONTACT_EMAIL,
  FAQS,
  jsonLdScriptProps,
  liturgyJsonLd,
  THESIS,
} from "@/lib/liturgy/seo";
import {
  COGNATES,
  DIALECT_NOTES,
  SCRIPTURE,
  SOURCES,
} from "@/lib/liturgy/language";

/**
 * /liturgy — what the translation is, who made it, and where to get it.
 *
 * A server component: nothing here needs state, so the page costs no client
 * JavaScript. UI copy is English, as agreed; the liturgy's own titles stay in
 * Slovak with a `lang` attribute.
 */

interface DownloadItem {
  href: string;
  title: string;
  meta: string;
}



/**
 * The songbook, generated by `npm run book`, plus the source document. The
 * thesis is listed separately because it is a different kind of thing —
 * scholarship behind the translation rather than a service book.
 */
const SONGBOOK_DOWNLOADS: DownloadItem[] = [
  {
    href: "/downloads/liturgy/spevnik-v1.1-a5.pdf",
    title: "Spevník v1.1 — print edition",
    meta: "PDF · A5 · ready to print and bind",
  },
  {
    href: "/downloads/liturgy/spevnik-v1.1.epub",
    title: "Spevník v1.1 — e-book",
    meta: "EPUB · for phones and e-readers",
  },
  {
    href: "/downloads/liturgy/spevnik-v1.1.docx",
    title: "Spevník v1.1 — source document",
    meta: "DOCX · the working file, with footnotes",
  },
];

/** Supplied separately from the songbook; not in the repository yet. */
const THESIS_DOWNLOAD: DownloadItem = {
  href: "/downloads/liturgy/rigorozna-praca-2024.pdf",
  title:
    "Liturgia sv. Jána Zlatoústeho a možnosti jej prekladu do stredoslovenského dialektu rómčiny",
  meta: "PDF · Rigorózna práca, PBF PU Prešov, 2024 · Slovak",
};

const REFERENCES = [
  {
    href: "https://arhiepiscopiaramnicului.ro/biroul-de-catehizare-rromilor/sfanta-liturghie-ortodoxa-limba-rromani",
    title: "Romanian Orthodox Divine Liturgy in Romani",
    meta: "Arhiepiscopia Râmnicului, 2016",
  },
  {
    href: null,
    title: "Serbian Romani Služebnik",
    meta: "Serbian Orthodox Church, Novi Sad, 1993 — printed only",
  },
] as const;

function DownloadRow({ item }: { item: DownloadItem }) {
  return (
    <li>
      <a
        href={item.href}
        download
        className="group flex items-center gap-4 rounded-lg border border-[var(--border-default)] bg-[var(--bg-card)] px-4 py-4 transition-colors hover:border-[var(--gold)]"
      >
        <Download
          className="size-5 shrink-0 text-[var(--gold)]"
          aria-hidden="true"
        />
        <span className="min-w-0 flex-1">
          <span className="block text-[15px] font-medium text-[var(--text-primary)]">
            {item.title}
          </span>
          <span className="block text-[13px] text-[var(--text-muted)]">
            {item.meta}
            {downloadSize(item.href) && ` · ${downloadSize(item.href)}`}
          </span>
        </span>
        <ArrowRight
          className="size-4 shrink-0 text-[var(--text-muted)] transition-transform group-hover:translate-x-0.5 group-hover:text-[var(--gold)]"
          aria-hidden="true"
        />
      </a>
    </li>
  );
}

/**
 * The site-wide section label, but as a real <h2> so the page has a heading
 * outline. It restates `components/SectionLabel`'s four styling rules rather
 * than wrapping it: that component renders a <div>, and a <div> inside an <h2>
 * is invalid — headings take phrasing content only.
 */
function SectionLabel({ children }: { children: string }) {
  return (
    <h2 className="mb-5 flex items-center gap-3">
      <span className="h-[14px] w-[3px] shrink-0 bg-[var(--gold)]" />
      <span className="text-[11px] font-semibold tracking-[2px] text-[var(--gold)] uppercase">
        {children}
      </span>
    </h2>
  );
}

/** The three things this text actually needs, in plain terms. */
const HELP = [
  {
    icon: Printer,
    title: "Printed books",
    body: "The PDF is free and ready for a printer. What a parish needs is enough bound copies to go round, so a congregation can sing together instead of listening to one person read.",
  },
  {
    icon: SpellCheck,
    title: "Romani readers",
    body: "Native speakers of the Central-Slovak dialect to read the draft and mark what sounds wrong. This is the scarcest of the three, and the most valuable.",
  },
  {
    icon: Mic,
    title: "Voices",
    body: "Singers to record the responses, so that people who do not read can still learn their part by ear — as most of this congregation always has.",
  },
] as const;

function Prose({ children }: { children: React.ReactNode }) {
  return (
    <p className="mb-5 text-[16px] leading-relaxed text-[var(--text-secondary)]">
      {children}
    </p>
  );
}

/** A figure with its caption — used for the "five groups / seven codes" row. */
function Stat({ value, label }: { value: string; label: string }) {
  return (
    <div>
      <p className="font-georgia text-[34px] leading-none text-[var(--gold)]">
        {value}
      </p>
      <p className="mt-2 text-[14px] leading-snug text-[var(--text-secondary)]">
        {label}
      </p>
    </div>
  );
}

export default function LiturgyPage({ locale }: { locale: Locale }) {
  const { meta } = LITURGY;
  const textPath = buildPath(locale, "liturgyText");
  const involvedPath = buildPath(locale, "getInvolved");

  return (
    <div className="min-h-screen bg-[var(--bg-primary)]">
      <script
        {...jsonLdScriptProps(
          liturgyJsonLd(
            locale,
            "Liturgy in Romani",
            "The Divine Liturgy of St John Chrysostom in the Central-Slovak dialect of Romani, translated by Martin Halík for the Christian Roma Mission."
          )
        )}
      />
      <Navbar activePage="liturgy" />

      <main>
        {/* Hero */}
        <section className="border-b border-[var(--border-default)] px-5 pt-32 pb-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <p className="mb-4 text-[11px] font-semibold tracking-[2px] text-[var(--gold)] uppercase">
              Liturgy in Romani
            </p>
            <h1 className="font-georgia text-[34px] leading-[1.15] text-[var(--text-primary)] sm:text-[52px]">
              The Divine Liturgy, in the language people pray in
            </h1>
            <p className="mt-6 text-[17px] leading-relaxed text-[var(--text-secondary)] sm:text-[19px]">
              The Divine Liturgy of St John Chrysostom, translated into the
              Central-Slovak dialect of Romani — so far as we know, the first
              such translation. It is served with the blessing of our bishop in
              the Roma communities of Markovce and Klenovec, and it is a working
              text: still being corrected, line by line, by the people who sing
              it.
            </p>

            <div className="mt-9 flex flex-wrap items-center gap-4">
              <Link
                href={textPath}
                className="inline-flex items-center gap-2 rounded-full bg-[var(--gold)] px-6 py-3 text-[14px] font-semibold tracking-[1px] text-[var(--on-accent)] uppercase transition-opacity hover:opacity-90"
              >
                <BookOpen className="size-4" aria-hidden="true" />
                Read the liturgy
              </Link>
              <span className="text-[13px] text-[var(--text-muted)]">
                Version {meta.version} · {meta.sourceDate}
              </span>
            </div>
          </div>
        </section>

        {/* What it is */}
        <section className="px-5 py-16 sm:px-6">
          <div className="mx-auto grid max-w-3xl gap-12 sm:grid-cols-2">
            <div>
              <SectionLabel>Who made it</SectionLabel>
              <dl className="space-y-4 text-[15px]">
                <div>
                  <dt className="text-[var(--text-muted)]">Translator</dt>
                  <dd className="text-[var(--text-primary)]">Martin Halík</dd>
                </div>
                <div>
                  <dt className="text-[var(--text-muted)]">Consultant</dt>
                  <dd className="text-[var(--text-primary)]">Ján Hero</dd>
                </div>
                <div>
                  <dt className="text-[var(--text-muted)]">Published by</dt>
                  <dd className="text-[var(--text-primary)]">
                    Kresťanská rómska misia
                  </dd>
                </div>
              </dl>
            </div>
            <div>
              <SectionLabel>This version</SectionLabel>
              <dl className="space-y-4 text-[15px]">
                <div>
                  <dt className="text-[var(--text-muted)]">Version</dt>
                  <dd className="text-[var(--text-primary)]">
                    {meta.version} · {meta.sourceDate}
                  </dd>
                </div>
                <div>
                  <dt className="text-[var(--text-muted)]">Contents</dt>
                  <dd className="text-[var(--text-primary)]">
                    {meta.counts.utterances} lines, {meta.counts.footnotes}{" "}
                    translator&rsquo;s notes
                  </dd>
                </div>
                <div>
                  <dt className="text-[var(--text-muted)]">Corrections</dt>
                  <dd>
                    <a
                      href="mailto:martin.halik@krm.sk"
                      className="text-[var(--gold)] hover:underline"
                    >
                      martin.halik@krm.sk
                    </a>
                  </dd>
                </div>
              </dl>
            </div>
          </div>
        </section>

        {/* Which Romani */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>Which Romani?</SectionLabel>
            <h3 className="font-georgia mb-5 text-[26px] leading-tight text-[var(--text-primary)] sm:text-[32px]">
              There is no such thing as “the” Romani language
            </h3>
            <Prose>
              Romani is a family, not a single tongue. Linguists sort it into
              five main dialect groups — Vlax, Balkan, Central, Northwestern and
              Northeastern — plus a handful of isolated varieties in Britain,
              Iberia and southern Italy. Seven of those varieties carry their own
              ISO language codes.
            </Prose>
            <Prose>
              This translation belongs to the Central group: it is{" "}
              <strong className="font-semibold text-[var(--text-primary)]">
                Carpathian Romani
              </strong>{" "}
              (<code className="text-[14px] text-[var(--gold)]">rmc</code>), and
              within that, the dialect spoken in{" "}
              <strong className="font-semibold text-[var(--text-primary)]">
                central Slovakia
              </strong>{" "}
              — the Romani of Klenovec and the Gemer region. That matters
              locally: Slovakia already has a New Testament in{" "}
              <em>eastern</em> Slovak Romani, and a whole Bible in Carpathian
              Romani. Neither is the speech of the villages this mission serves,
              and the difference is not academic — it is the difference between a
              text people follow and a text people pray.
            </Prose>

            <div className="mt-10 grid grid-cols-2 gap-8 border-t border-[var(--border-default)] pt-8 sm:grid-cols-4">
              <Stat value="5" label="main dialect groups" />
              <Stat value="7" label="varieties with their own ISO code" />
              <Stat value="rmc" label="the code for Carpathian Romani" />
              <Stat value="~1000" label="years since the language left India" />
            </div>
          </div>
        </section>

        {/* A language from India */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>A language that came from India</SectionLabel>
            <Prose>
              Romani is an Indo-Aryan language. It left the northern Indian
              subcontinent around a thousand years ago and it never stopped being
              Indian — it was by studying Romani that European scholars first
              worked out where the Roma had come from. Its closest living
              relatives are Hindi, Urdu and Punjabi, and the family resemblance
              is not buried in the grammar. It is sitting in the plainest words
              of the Liturgy.
            </Prose>
            <Prose>
              A Roma man from Klenovec and a man from Delhi or Lahore cannot hold
              a conversation — a thousand years and half a continent of borrowed
              vocabulary lie between them. But they will both recognise the word
              for water, for house, for brother, for name. Every word below is in
              the text of this Liturgy; the count is how often its root appears.
            </Prose>

            <div className="mt-8 overflow-hidden rounded-lg border border-[var(--border-default)]">
              <table className="w-full text-left text-[15px]">
                <caption className="sr-only">
                  Words in this Liturgy and their Hindi relatives
                </caption>
                <thead>
                  <tr className="border-b border-[var(--border-default)] bg-[var(--bg-card)]">
                    <th scope="col" className="px-4 py-3 text-[11px] font-semibold tracking-[1px] text-[var(--text-muted)] uppercase">
                      In the Liturgy
                    </th>
                    <th scope="col" className="px-4 py-3 text-[11px] font-semibold tracking-[1px] text-[var(--text-muted)] uppercase">
                      Means
                    </th>
                    <th scope="col" className="px-4 py-3 text-[11px] font-semibold tracking-[1px] text-[var(--text-muted)] uppercase">
                      Hindi / Urdu
                    </th>
                    <th scope="col" className="hidden px-4 py-3 text-right text-[11px] font-semibold tracking-[1px] text-[var(--text-muted)] uppercase sm:table-cell">
                      Times
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {COGNATES.map((c) => (
                    <tr
                      key={c.romani}
                      className="border-b border-[var(--border-default)] last:border-0"
                    >
                      <td className="px-4 py-3 font-medium text-[var(--text-primary)]" lang="rom">
                        {c.romani}
                      </td>
                      <td className="px-4 py-3 text-[var(--text-secondary)]">
                        {c.gloss}
                      </td>
                      <td className="px-4 py-3 text-[var(--text-secondary)]" lang="hi-Latn">
                        {c.hindi}
                      </td>
                      <td className="hidden px-4 py-3 text-right text-[var(--text-muted)] tabular-nums sm:table-cell">
                        {c.occurrences}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <p className="mt-6 rounded-lg border-l-2 border-[var(--gold)] bg-[var(--bg-card)] px-5 py-4 text-[15px] leading-relaxed text-[var(--text-secondary)]">
              The Trinity, in this Liturgy, is named half in Indian and half in
              Slavonic:{" "}
              <strong className="font-semibold text-[var(--text-primary)]" lang="rom">
                le Dadéskero, le Čhavéskero thaj le Svetos Duchóskero
              </strong>{" "}
              — Father and Son from words the Roma carried out of India, Spirit
              from the Church Slavonic of the Byzantine rite they were baptised
              into. A thousand years of the journey is in one line.
            </p>
          </div>
        </section>

        {/* Differences between dialects */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>What changes from village to village</SectionLabel>
            <Prose>
              Every line of this translation is a choice, and the translator
              recorded the alternatives in footnotes as he went — what the
              Serbian and Romanian Romani liturgies say, what the older people in
              Klenovec say, what they say a valley away in Gemer. These are the
              interesting differences: not spelling, but a different word chosen
              for the same prayer.
            </Prose>

            <ul className="mt-8 space-y-4">
              {DIALECT_NOTES.map((d) => (
                <li
                  key={d.note}
                  className="rounded-lg border border-[var(--border-default)] bg-[var(--bg-card)] px-5 py-4"
                >
                  <p className="flex flex-wrap items-baseline gap-x-3">
                    <span
                      className="text-[17px] font-semibold text-[var(--text-primary)]"
                      lang="rom"
                    >
                      {d.term}
                    </span>
                    <span className="text-[14px] text-[var(--text-muted)]">
                      note {d.note}
                    </span>
                  </p>
                  <p className="mt-1 text-[15px] text-[var(--text-secondary)]">
                    {d.gloss}
                  </p>
                  <dl className="mt-3 space-y-1 border-t border-[var(--border-default)] pt-3 text-[14px]">
                    {d.variants.map((v) => (
                      <div key={v.where} className="flex flex-wrap gap-x-2">
                        <dt className="text-[var(--text-muted)]">{v.where}:</dt>
                        <dd className="text-[var(--text-primary)]" lang="rom">
                          {v.form}
                        </dd>
                      </div>
                    ))}
                  </dl>
                </li>
              ))}
            </ul>

            <p className="mt-6 text-[15px] leading-relaxed text-[var(--text-secondary)]">
              And one that shows what is at stake in getting it wrong. Just
              before the Creed the priest calls{" "}
              <strong className="font-semibold text-[var(--text-primary)]" lang="rom">
                Vudar! Vudar!
              </strong>{" "}
              — “The doors! The doors!”. The translator marks it with a warning:
              clipped in ordinary speech, <em lang="rom">vudár</em> is heard as{" "}
              <em lang="rom">budár</em> — the toilet (note 16). A vowel length is
              the whole difference between reverence and a joke at the back of
              the church.
            </p>
          </div>
        </section>

        {/* Scripture in Romani */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>Scripture in Romani</SectionLabel>
            <Prose>
              The Roma have had parts of the Bible in their own speech since
              1837, but almost always one variety at a time, and almost always
              from outside the Orthodox Church. These are the landmarks — not a
              complete inventory, since portions exist in many more varieties
              than are catalogued anywhere publicly.
            </Prose>

            <ol className="mt-8 space-y-0">
              {SCRIPTURE.map((s) => (
                <li
                  key={`${s.variety}-${s.year}`}
                  className={`border-l-2 py-4 pl-5 ${
                    s.ours
                      ? "border-[var(--gold)]"
                      : "border-[var(--border-strong)]"
                  }`}
                >
                  <p className="flex flex-wrap items-baseline gap-x-3">
                    <span className="font-georgia text-[18px] text-[var(--gold)] tabular-nums">
                      {s.year}
                    </span>
                    <span className="text-[16px] font-medium text-[var(--text-primary)]">
                      {s.variety}
                    </span>
                    {s.iso && (
                      <code className="text-[13px] text-[var(--text-muted)]">
                        {s.iso}
                      </code>
                    )}
                  </p>
                  <p className="mt-1 text-[15px] leading-relaxed text-[var(--text-secondary)]">
                    {s.what}
                    {s.who !== "—" && (
                      <span className="text-[var(--text-muted)]"> · {s.who}</span>
                    )}
                  </p>
                </li>
              ))}
            </ol>

            <p className="mt-8 text-[15px] leading-relaxed text-[var(--text-secondary)]">
              Which is why this one matters: it is the Divine Liturgy rather than
              Scripture, it is Orthodox, and it is in the dialect actually spoken
              in the villages where it is sung.
            </p>

            <details className="mt-8 rounded-lg border border-[var(--border-default)] bg-[var(--bg-card)]">
              <summary className="px-5 py-3 text-[13px] font-medium tracking-[1px] text-[var(--text-secondary)] uppercase">
                Sources
              </summary>
              <ul className="space-y-2 px-5 pb-4 text-[14px] text-[var(--text-secondary)]">
                {SOURCES.map((source) => (
                  <li key={source.label}>
                    {source.href ? (
                      <a
                        href={source.href}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="hover:text-[var(--gold)] hover:underline"
                      >
                        {source.label}
                      </a>
                    ) : (
                      source.label
                    )}
                  </li>
                ))}
              </ul>
            </details>
          </div>
        </section>

        {/* Downloads */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>Download the songbook</SectionLabel>
            <ul className="space-y-3">
              {SONGBOOK_DOWNLOADS.filter((item) => hasDownload(item.href)).map(
                (item) => (
                  <DownloadRow key={item.href} item={item} />
                )
              )}
            </ul>

            <h3 className="mt-12 mb-5 text-[11px] font-semibold tracking-[2px] text-[var(--gold)] uppercase">
              The thesis behind the translation
            </h3>
            <p className="mb-4 text-[14px] leading-relaxed text-[var(--text-secondary)]">
              The academic work behind the translation: what the Liturgy asks of
              a language, which choices the Romani of central Slovakia makes
              possible, and where it has to borrow. Written in Slovak.
            </p>
            {hasDownload(THESIS_DOWNLOAD.href) ? (
              <ul className="space-y-3">
                <DownloadRow item={THESIS_DOWNLOAD} />
              </ul>
            ) : (
              <p className="rounded-lg border border-[var(--border-default)] bg-[var(--bg-card)] px-4 py-4 text-[14px] leading-relaxed text-[var(--text-secondary)]">
                <cite className="not-italic" lang="sk">
                  Halík, M. (2024). <i>{THESIS.title}</i>. Rigorózna práca, PBF
                  PU, Prešov.
                </cite>
                <span className="mt-2 block text-[13px] text-[var(--text-muted)]">
                  The PDF is not published here yet.
                </span>
              </p>
            )}
          </div>
        </section>

        {/* Reference translations */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>Other Romani translations</SectionLabel>
            <p className="mb-6 max-w-2xl text-[15px] leading-relaxed text-[var(--text-secondary)]">
              This work does not stand alone. Two earlier Orthodox translations
              into other Romani dialects were consulted throughout, and the
              footnotes refer to them often.
            </p>
            <ul className="space-y-3">
              {REFERENCES.map((ref) => (
                <li
                  key={ref.title}
                  className="rounded-lg border border-[var(--border-default)] bg-[var(--bg-card)] px-4 py-4"
                >
                  {ref.href ? (
                    <a
                      href={ref.href}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="group flex items-start gap-3"
                    >
                      <ExternalLink
                        className="mt-0.5 size-4 shrink-0 text-[var(--gold)]"
                        aria-hidden="true"
                      />
                      <span>
                        <span className="block text-[15px] font-medium text-[var(--text-primary)] group-hover:text-[var(--gold)]">
                          {ref.title}
                        </span>
                        <span className="block text-[13px] text-[var(--text-muted)]">
                          {ref.meta}
                        </span>
                      </span>
                    </a>
                  ) : (
                    <div className="flex items-start gap-3">
                      <FileText
                        className="mt-0.5 size-4 shrink-0 text-[var(--text-muted)]"
                        aria-hidden="true"
                      />
                      <span>
                        <span className="block text-[15px] font-medium text-[var(--text-primary)]">
                          {ref.title}
                        </span>
                        <span className="block text-[13px] text-[var(--text-muted)]">
                          {ref.meta}
                        </span>
                      </span>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* How you can help */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>How you can help</SectionLabel>
            <h3 className="font-georgia mb-5 text-[26px] leading-tight text-[var(--text-primary)] sm:text-[32px]">
              A service book is not finished when the translating stops
            </h3>
            <Prose>
              It is finished when a grandmother in Klenovec can hold it open and
              sing her part without being handed a Slovak book she only half
              follows. Three things stand between here and there, and none of
              them is translation.
            </Prose>

            <ul className="mt-8 grid gap-4 sm:grid-cols-3">
              {HELP.map((help) => (
                <li
                  key={help.title}
                  className="rounded-lg border border-[var(--border-default)] bg-[var(--bg-card)] p-5"
                >
                  <help.icon
                    className="mb-3 size-5 text-[var(--gold)]"
                    aria-hidden="true"
                  />
                  <p className="mb-2 text-[16px] font-medium text-[var(--text-primary)]">
                    {help.title}
                  </p>
                  <p className="text-[14px] leading-relaxed text-[var(--text-secondary)]">
                    {help.body}
                  </p>
                </li>
              ))}
            </ul>

            <div className="mt-8 flex flex-wrap items-center gap-4">
              <Link
                href={involvedPath}
                className="inline-flex items-center gap-2 rounded-full bg-[var(--gold)] px-6 py-3 text-[14px] font-semibold tracking-[1px] text-[var(--on-accent)] uppercase transition-opacity hover:opacity-90"
              >
                <HandHeart className="size-4" aria-hidden="true" />
                Support this work
              </Link>
              <a
                href={`mailto:${CONTACT_EMAIL}?subject=Romani%20liturgy%20%E2%80%94%20I%20can%20help`}
                className="inline-flex items-center gap-2 rounded-full border border-[var(--border-strong)] px-6 py-3 text-[14px] font-semibold tracking-[1px] text-[var(--text-secondary)] uppercase transition-colors hover:border-[var(--gold)] hover:text-[var(--gold)]"
              >
                Offer corrections or your voice
              </a>
            </div>
          </div>
        </section>

        {/* Questions */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>Questions</SectionLabel>
            <dl className="divide-y divide-[var(--border-default)]">
              {FAQS.map((faq) => (
                <div key={faq.q} className="py-5 first:pt-0">
                  <dt className="mb-2 text-[17px] font-medium text-[var(--text-primary)]">
                    {faq.q}
                  </dt>
                  <dd className="text-[15px] leading-relaxed text-[var(--text-secondary)]">
                    {faq.a}
                  </dd>
                </div>
              ))}
            </dl>
          </div>
        </section>

        {/* How to cite */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>How to cite</SectionLabel>
            <Prose>
              This is a named piece of scholarship, not an anonymous web page.
              If you quote the translation or write about it, please cite it —
              in whichever of these forms your work uses.
            </Prose>
            <div className="space-y-3">
              {CITATIONS.map((citation) => (
                <div
                  key={citation.key}
                  className="rounded-lg border-l-2 border-[var(--gold)] bg-[var(--bg-card)] px-5 py-4"
                >
                  <p className="mb-2 text-[11px] font-semibold tracking-[1.5px] text-[var(--text-muted)] uppercase">
                    {citation.label}
                  </p>
                  {citation.key === "bibtex" ? (
                    <pre className="text-[13px] leading-relaxed break-words whitespace-pre-wrap text-[var(--text-secondary)]">
                      <code>{citation.text}</code>
                    </pre>
                  ) : (
                    <cite className="text-[15px] leading-relaxed not-italic text-[var(--text-secondary)]">
                      {citation.text}
                    </cite>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>

      <CTASection />
      <Footer />
    </div>
  );
}
