import { existsSync } from "node:fs";
import { join } from "node:path";
import { ArrowRight, BookOpen, Download, ExternalLink, FileText } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CTASection from "@/components/CTASection";
import { LITURGY } from "@/lib/liturgy/content";

/**
 * /liturgy — what the translation is, who made it, and where to get it.
 *
 * A server component: nothing here needs state, so the page costs no client
 * JavaScript. UI copy is English, as agreed; the liturgy's own titles stay in
 * Slovak with a `lang` attribute.
 */

interface DownloadItem {
  href: string;
  title: string;
  meta: string;
}

/**
 * Whether a download actually exists in `public/`.
 *
 * The songbook files are generated by `npm run book`, and the thesis PDF has
 * not been supplied yet. A download row that 404s is worse than one that is
 * absent, so each is checked at render time on the server and simply left out
 * until the file is there.
 */
function isPresent(href: string): boolean {
  return existsSync(join(process.cwd(), "public", href));
}

/**
 * The songbook, generated by `npm run book`, plus the source document. The
 * thesis is listed separately because it is a different kind of thing —
 * scholarship behind the translation rather than a service book.
 */
const SONGBOOK_DOWNLOADS: DownloadItem[] = [
  {
    href: "/downloads/liturgy/spevnik-v1.1-a5.pdf",
    title: "Spevník v1.1 — print edition",
    meta: "PDF · A5 · ready to print and bind",
  },
  {
    href: "/downloads/liturgy/spevnik-v1.1.epub",
    title: "Spevník v1.1 — e-book",
    meta: "EPUB · for phones and e-readers",
  },
  {
    href: "/downloads/liturgy/spevnik-v1.1.docx",
    title: "Spevník v1.1 — source document",
    meta: "DOCX · the working file, with footnotes",
  },
];

/** Supplied separately from the songbook; not in the repository yet. */
const THESIS: DownloadItem = {
  href: "/downloads/liturgy/rigorozna-praca-2024.pdf",
  title:
    "Liturgia sv. Jána Zlatoústeho a možnosti jej prekladu do stredoslovenského dialektu rómčiny",
  meta: "PDF · Rigorózna práca, PBF PU Prešov, 2024 · Slovak",
};

const REFERENCES = [
  {
    href: "https://arhiepiscopiaramnicului.ro/biroul-de-catehizare-rromilor/sfanta-liturghie-ortodoxa-limba-rromani",
    title: "Romanian Orthodox Divine Liturgy in Romani",
    meta: "Arhiepiscopia Râmnicului, 2016",
  },
  {
    href: null,
    title: "Serbian Romani Služebnik",
    meta: "Serbian Orthodox Church, Novi Sad, 1993 — printed only",
  },
] as const;

function DownloadRow({ item }: { item: DownloadItem }) {
  return (
    <li>
      <a
        href={item.href}
        download
        className="group flex items-center gap-4 rounded-lg border border-[var(--border-default)] bg-[var(--bg-card)] px-4 py-4 transition-colors hover:border-[var(--gold)]"
      >
        <Download
          className="size-5 shrink-0 text-[var(--gold)]"
          aria-hidden="true"
        />
        <span className="min-w-0 flex-1">
          <span className="block text-[15px] font-medium text-[var(--text-primary)]">
            {item.title}
          </span>
          <span className="block text-[13px] text-[var(--text-muted)]">
            {item.meta}
          </span>
        </span>
        <ArrowRight
          className="size-4 shrink-0 text-[var(--text-muted)] transition-transform group-hover:translate-x-0.5 group-hover:text-[var(--gold)]"
          aria-hidden="true"
        />
      </a>
    </li>
  );
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="mb-5 text-[11px] font-semibold tracking-[2px] text-[var(--gold)] uppercase">
      {children}
    </h2>
  );
}

export default function LiturgyPage() {
  const { meta } = LITURGY;

  return (
    <div className="min-h-screen bg-[var(--bg-primary)]">
      <Navbar activePage="liturgy" />

      <main>
        {/* Hero */}
        <section className="border-b border-[var(--border-default)] px-5 pt-32 pb-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <p className="mb-4 text-[11px] font-semibold tracking-[2px] text-[var(--gold)] uppercase">
              Liturgy in Romani
            </p>
            <h1 className="font-georgia text-[34px] leading-[1.15] text-[var(--text-primary)] sm:text-[52px]">
              The Divine Liturgy, in the language people pray in
            </h1>
            <p className="mt-6 text-[17px] leading-relaxed text-[var(--text-secondary)] sm:text-[19px]">
              The Divine Liturgy of St John Chrysostom, translated into the
              Central-Slovak dialect of Romani — so far as we know, the first
              such translation. It is served with the blessing of our bishop in
              the Roma communities of Markovce and Klenovec, and it is a working
              text: still being corrected, line by line, by the people who sing
              it.
            </p>

            <div className="mt-9 flex flex-wrap items-center gap-4">
              <a
                href="text"
                className="inline-flex items-center gap-2 rounded-full bg-[var(--gold)] px-6 py-3 text-[14px] font-semibold tracking-[1px] text-[var(--on-accent)] uppercase transition-opacity hover:opacity-90"
              >
                <BookOpen className="size-4" aria-hidden="true" />
                Read the liturgy
              </a>
              <span className="text-[13px] text-[var(--text-muted)]">
                Version {meta.version} · {meta.sourceDate}
              </span>
            </div>
          </div>
        </section>

        {/* What it is */}
        <section className="px-5 py-16 sm:px-6">
          <div className="mx-auto grid max-w-3xl gap-12 sm:grid-cols-2">
            <div>
              <SectionLabel>Who made it</SectionLabel>
              <dl className="space-y-4 text-[15px]">
                <div>
                  <dt className="text-[var(--text-muted)]">Translator</dt>
                  <dd className="text-[var(--text-primary)]">Martin Halík</dd>
                </div>
                <div>
                  <dt className="text-[var(--text-muted)]">Consultant</dt>
                  <dd className="text-[var(--text-primary)]">Ján Hero</dd>
                </div>
                <div>
                  <dt className="text-[var(--text-muted)]">Published by</dt>
                  <dd className="text-[var(--text-primary)]">
                    Kresťanská rómska misia
                  </dd>
                </div>
              </dl>
            </div>
            <div>
              <SectionLabel>This version</SectionLabel>
              <dl className="space-y-4 text-[15px]">
                <div>
                  <dt className="text-[var(--text-muted)]">Version</dt>
                  <dd className="text-[var(--text-primary)]">
                    {meta.version} · {meta.sourceDate}
                  </dd>
                </div>
                <div>
                  <dt className="text-[var(--text-muted)]">Contents</dt>
                  <dd className="text-[var(--text-primary)]">
                    {meta.counts.utterances} lines, {meta.counts.footnotes}{" "}
                    translator&rsquo;s notes
                  </dd>
                </div>
                <div>
                  <dt className="text-[var(--text-muted)]">Corrections</dt>
                  <dd>
                    <a
                      href="mailto:martin.halik@krm.sk"
                      className="text-[var(--gold)] hover:underline"
                    >
                      martin.halik@krm.sk
                    </a>
                  </dd>
                </div>
              </dl>
            </div>
          </div>
        </section>

        {/* Downloads */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>Download the songbook</SectionLabel>
            <ul className="space-y-3">
              {SONGBOOK_DOWNLOADS.filter((item) => isPresent(item.href)).map(
                (item) => (
                  <DownloadRow key={item.href} item={item} />
                )
              )}
            </ul>

            <h3 className="mt-12 mb-5 text-[11px] font-semibold tracking-[2px] text-[var(--gold)] uppercase">
              The thesis behind the translation
            </h3>
            <p className="mb-4 text-[14px] leading-relaxed text-[var(--text-secondary)]">
              The academic work behind the translation: what the Liturgy asks of
              a language, which choices the Romani of central Slovakia makes
              possible, and where it has to borrow. Written in Slovak.
            </p>
            {isPresent(THESIS.href) ? (
              <ul className="space-y-3">
                <DownloadRow item={THESIS} />
              </ul>
            ) : (
              <p className="rounded-lg border border-[var(--border-default)] bg-[var(--bg-card)] px-4 py-4 text-[14px] leading-relaxed text-[var(--text-secondary)]">
                <cite className="not-italic" lang="sk">
                  Halík, M. (2024). <i>{THESIS.title}</i>. Rigorózna práca, PBF
                  PU, Prešov.
                </cite>
                <span className="mt-2 block text-[13px] text-[var(--text-muted)]">
                  The PDF is not published here yet.
                </span>
              </p>
            )}
          </div>
        </section>

        {/* Reference translations */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>Other Romani translations</SectionLabel>
            <p className="mb-6 max-w-2xl text-[15px] leading-relaxed text-[var(--text-secondary)]">
              This work does not stand alone. Two earlier Orthodox translations
              into other Romani dialects were consulted throughout, and the
              footnotes refer to them often.
            </p>
            <ul className="space-y-3">
              {REFERENCES.map((ref) => (
                <li
                  key={ref.title}
                  className="rounded-lg border border-[var(--border-default)] bg-[var(--bg-card)] px-4 py-4"
                >
                  {ref.href ? (
                    <a
                      href={ref.href}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="group flex items-start gap-3"
                    >
                      <ExternalLink
                        className="mt-0.5 size-4 shrink-0 text-[var(--gold)]"
                        aria-hidden="true"
                      />
                      <span>
                        <span className="block text-[15px] font-medium text-[var(--text-primary)] group-hover:text-[var(--gold)]">
                          {ref.title}
                        </span>
                        <span className="block text-[13px] text-[var(--text-muted)]">
                          {ref.meta}
                        </span>
                      </span>
                    </a>
                  ) : (
                    <div className="flex items-start gap-3">
                      <FileText
                        className="mt-0.5 size-4 shrink-0 text-[var(--text-muted)]"
                        aria-hidden="true"
                      />
                      <span>
                        <span className="block text-[15px] font-medium text-[var(--text-primary)]">
                          {ref.title}
                        </span>
                        <span className="block text-[13px] text-[var(--text-muted)]">
                          {ref.meta}
                        </span>
                      </span>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* How to cite */}
        <section className="border-t border-[var(--border-default)] px-5 py-16 sm:px-6">
          <div className="mx-auto max-w-3xl">
            <SectionLabel>How to cite</SectionLabel>
            <blockquote className="rounded-lg border-l-2 border-[var(--gold)] bg-[var(--bg-card)] px-5 py-4 text-[15px] leading-relaxed text-[var(--text-secondary)]">
              <cite className="not-italic" lang="sk">
                Halík, M. (2024). <i>Liturgia sv. Jána Zlatoústeho a možnosti
                jej prekladu do stredoslovenského dialektu rómčiny</i>.
                Rigorózna práca, PBF PU, Prešov.
              </cite>
            </blockquote>
          </div>
        </section>
      </main>

      <CTASection />
      <Footer />
    </div>
  );
}
