import BOOK from "@/content/book/book.json";
import BOOK_FILES from "@/lib/data/book-files.json";
import AUDIOBOOK_EN from "@/lib/data/audiobook-en.json";
import { LOCALES, type Locale } from "@/lib/i18n/locales";

export type BookFormat = "epub" | "pdf";
export type SubscribeChannel = "email" | "sms";

export interface BookFile {
  file: string;
  bytes: number;
}

export interface BookEditionFiles {
  epub: BookFile;
  pdf: BookFile;
  cover: string;
  words: number;
}

export interface BookTitle {
  title: string;
  subtitle: string;
}

export interface AudiobookChapter {
  title: string;
  start: number;
}

export interface Audiobook {
  voice: string;
  duration: number;
  m4b: BookFile;
  mp3: BookFile;
  chapters: AudiobookChapter[];
}

// Generated by `python3 scripts/build-audiobook.py` (English edition only);
// `null` until the audiobook has been built.
export const AUDIOBOOK = AUDIOBOOK_EN as Audiobook | null;

export function formatDuration(seconds: number, template: string): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.round((seconds % 3600) / 60);
  return template.replace("{hours}", String(hours)).replace("{minutes}", String(minutes));
}

export function formatTimestamp(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const mm = String(m).padStart(h ? 2 : 1, "0");
  return `${h ? `${h}:` : ""}${mm}:${String(s).padStart(2, "0")}`;
}

// Generated by `node scripts/build-ebooks.mjs` — only locales that have been
// built appear here, so a missing translation never shows a broken link.
const EDITION_FILES = BOOK_FILES as Partial<Record<Locale, BookEditionFiles>>;

export const BOOK_LOCALES: Locale[] = LOCALES.map((l) => l.code).filter(
  (code) => EDITION_FILES[code] !== undefined
);

export const SEND_TO_KINDLE_URL = "https://www.amazon.com/sendtokindle";

export const BOOK_UNLOCK_STORAGE_KEY = "roma-book-unlocked";

export function getBookFiles(locale: Locale): BookEditionFiles | null {
  return EDITION_FILES[locale] ?? null;
}

export function getBookTitle(locale: Locale): BookTitle {
  const editions = BOOK.editions as Record<string, BookTitle>;
  const edition = editions[locale] ?? editions.en;
  return { title: edition.title, subtitle: edition.subtitle };
}

export function isBookLocale(value: unknown): value is Locale {
  return typeof value === "string" && BOOK_LOCALES.includes(value as Locale);
}

// Site language if that edition exists, otherwise English, otherwise the
// Slovak original.
export function defaultBookLocale(siteLocale: Locale): Locale {
  if (isBookLocale(siteLocale)) return siteLocale;
  if (isBookLocale("en")) return "en";
  return BOOK_LOCALES[0] ?? "sk";
}

const EMAIL_PATTERN = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;

export function isValidEmail(value: string): boolean {
  return value.length <= 254 && EMAIL_PATTERN.test(value.trim());
}

// Accepts "+421 900 123 456", "00421-900-123-456", "(+49) 151 2345678"…
// Returns E.164 ("+421900123456") or null.
export function normalizePhone(value: string): string | null {
  const compact = value.trim().replace(/[\s().\-/]/g, "").replace(/^00/, "+");
  return /^\+[1-9]\d{7,14}$/.test(compact) ? compact : null;
}

export function formatFileSize(bytes: number, locale: Locale): string {
  const mb = bytes / (1024 * 1024);
  const format = (n: number) =>
    new Intl.NumberFormat(locale, { maximumFractionDigits: 1 }).format(n);
  return mb >= 1 ? `${format(mb)} MB` : `${format(Math.max(1, Math.round(bytes / 1024)))} KB`;
}
